# Generated by Django 5.2.5 on 2025-08-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='source_food_id',
            field=models.CharField(blank=True, help_text='ID from the API (nullable for custom/local foods)', max_length=100, null=True),
        ),
    ]
