# Generated by Django 5.2.5 on 2025-08-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_fooditem_source_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='source_food_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
